In [ ]:
# Pytorch Basic Tensor Manipulation 1 (1-1)

In [ ]:
import numpy as np
import torch

In [ ]:
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2],t[3:])

[0. 1. 2. 3. 4. 5. 6.]
Rank of t :  1
Shape of t :  (7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [ ]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t :  2
Shape of t :  (4, 3)


In [ ]:
# 1D Array with PyTorch
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0],t[1],t[-1]) # element
print(t[2:5],t[4:-1]) # slicing
print(t[:2],t[3:]) # slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2D Array with PyTorch
t=torch.FloatTensor([[1.,2.,3.],
                    [4.,5.,6.],
                    [7.,8.,9.],
                    [10.,11.,12.]
                    ])
print(t)
print(t.dim()) # rank
print(t.size()) # shape
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1]) # 맨마지막만 제외

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# Broadcasting (다른 차원끼리 계산하기)
# for same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)
# for vector + scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
print(m1+m2) # m2가 [[3,3]]으로 자동 변환
# for 2x1vector + 1x2vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2) # [[1,2],[1,2]]+[[3,3],[4,4]]

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# Mul vs Matmul
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print(m1.matmul(m2)) # 2x1
print(m1.mul(m2)) # 2x2

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# Max
t=torch.FloatTensor([[1,2],[3,4]])
print(t.max())
print(t.max(dim=0)) # max, argmax 순서
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
# Mean
t=torch.FloatTensor([1,2])
print(t.mean())
# mean()은 integer, long에 대해 사용 불가
t=torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)
# 2x2
t=torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0)) # dim 0을 없앰 (2x2 -> 1x2)
print(t.mean(dim=1)) # (2x2 -> 2x1)
print(t.mean(dim=-1))

tensor(1.5000)
Can only calculate the mean of floating types. Got Long instead.
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
# Sum
t=torch.FloatTensor([[1,2],[3,4]])
print(t.sum())
print(t.sum(dim=0)) # 2x2 -> 1x2
print(t.sum(dim=1)) # 2x2 -> 2x1
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
# Pytorch Basic Tensor Manipulation 2 (1-2)

In [ ]:
# View (numpy에서의 Reshape)
t=np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]) # 2x2x3
ft=torch.FloatTensor(t)
print(ft.shape)
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)
print(ft.view([-1,1,3])) # -1의 의미: 모르겠다 알아서 적절히
print(ft.view([-1,1,3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
# Squeeze (쥐어짜서 없애줌 특히 해당 dim의 element가 1개일 때 해당 dim 없애기)
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# Unsqueeze (dim 반드시 명시할 것!)
ft=torch.FloatTensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0)) # dim=0
print(ft.unsqueeze(0).shape)
print(ft.view(1,-1)) # 뒤에는 모르겠고 처음에 1을 넣어라 (unsqueeze(0)과 동일)
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
print(ft.unsqueeze(-1))

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])


In [ ]:
# Type Casting (Type 바꿔주기)
lt=torch.LongTensor([1,2,3,4]) # 정수값
print(lt)
print(lt.float())
bt=torch.ByteTensor([True,False,False,True])
# ex) bt=(lt==3) -> bt=(0,0,1,0)
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [ ]:
# Concatenate (이어붙이기)
x=torch.FloatTensor([[1,2],[3,4]]) # 2x2
y=torch.FloatTensor([[5,6],[7,8]]) # 2x2
print(torch.cat([x,y],dim=0)) # dim0이 늘어남 -> 4x2
print(torch.cat([x,y],dim=1)) # dim1이 늘어남 -> 2x4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# Stacking (Concatenate를 더 편리하게)
x=torch.FloatTensor([1,4]) # (2,)
y=torch.FloatTensor([2,5]) # (2,)
z=torch.FloatTensor([3,6]) # (2,)
print(torch.stack([x,y,z])) # 쌓기 -> (3,2)
print(torch.stack([x,y,z],dim=1)) # -> (2,3)
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
#                (1,2)          (1,2)          (1,2)
# 즉 unsqueeze한 후 dim=0에 대해 cat한 것과 같음 -> (3.2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
# Ones and Zeros
x=torch.FloatTensor([[0,1,2],[2,1,0]]) # (2,3)
print(torch.ones_like(x)) # x와 shape도 같고 device도 같음
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# In-place Operation
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.)) # 정답값은 임의의 메모리에 들어감
print(x)
print(x.mul_(2.)) # _ is in-place operation -> 정답값이 기존 tensor로 들어감
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [ ]:
# Linea Regression (2)

In [ ]:
import torch.optim as optim
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.01)

In [ ]:
nb_epochs=1000
for epoch in range(1,nb_epochs+1) :
  hypothesis=x_train*W+b
  cost=torch.mean((hypothesis-y_train)**2)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
print(W,b)

tensor([1.9974], requires_grad=True) tensor([0.0060], requires_grad=True)


In [ ]:
# Deeper Look at GD (3)

In [ ]:
# 데이터
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])
# 모델 초기화
W=torch.zeros(1)
# learning rate 설정
lr=0.1
nb_epochs=10
for epoch in range(1,nb_epochs+1) :
  # H(x) 계산
  hypothesis=x_train*W
  # cost gradient 계산
  cost=torch.mean((hypothesis-y_train)**2)
  gradient=2*torch.mean((W*x_train-y_train)*x_train)
  # cost gradient로 H(x) 계산
  W-=lr*gradient
  # 결과 출력
  print('Epoch{:4d}/{} W:{:.3f},Cost:{:.6f}'.format(
      epoch,nb_epochs,W.item(),cost.item()
  ))

Epoch   1/10 W:1.867,Cost:18.666666
Epoch   2/10 W:1.991,Cost:0.082963
Epoch   3/10 W:1.999,Cost:0.000369
Epoch   4/10 W:2.000,Cost:0.000002
Epoch   5/10 W:2.000,Cost:0.000000
Epoch   6/10 W:2.000,Cost:0.000000
Epoch   7/10 W:2.000,Cost:0.000000
Epoch   8/10 W:2.000,Cost:0.000000
Epoch   9/10 W:2.000,Cost:0.000000
Epoch  10/10 W:2.000,Cost:0.000000


In [ ]:
# torch.optim으로 gradient descent!
# 데이터
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])
# 모델 초기화
W=torch.zeros(1,requires_grad=True)
# optimizer 설정
optimizer=optim.SGD([W],lr=0.15)
nb_epochs=10
for epoch in range(1,nb_epochs+1) :
  # H(x) 계산
  hypothesis=x_train*W
  # cost gradient 계산
  cost=torch.mean((hypothesis-y_train)**2)
  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  # 결과 출력
  print('Epoch{:4d}/{} W:{:.3f},Cost:{:.6f}'.format(
      epoch,nb_epochs,W.item(),cost.item()
  ))

Epoch   1/10 W:2.800,Cost:18.666666
Epoch   2/10 W:1.680,Cost:2.986668
Epoch   3/10 W:2.128,Cost:0.477867
Epoch   4/10 W:1.949,Cost:0.076459
Epoch   5/10 W:2.020,Cost:0.012233
Epoch   6/10 W:1.992,Cost:0.001957
Epoch   7/10 W:2.003,Cost:0.000313
Epoch   8/10 W:1.999,Cost:0.000050
Epoch   9/10 W:2.001,Cost:0.000008
Epoch  10/10 W:2.000,Cost:0.000001


In [ ]:
# Multivariable Linear Regression (4-1)

In [ ]:
# 데이터
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
# 모델 초기화
W=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
# optimizer 설정
optimizer=optim.SGD([W,b],lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
  # H(x) 계산
  hypothesis=x_train.matmul(W)+b
  # cost 계산
  cost=torch.mean((hypothesis-y_train)**2)
  # cost로 H(x) 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  # 결과 출력
  print('Epoch{:4d}/{} Cost:{:.6f}'.format(
      epoch,nb_epochs,cost.item()
  ))

Epoch   0/20 Cost:29661.800781
Epoch   1/20 Cost:9298.520508
Epoch   2/20 Cost:2915.712402
Epoch   3/20 Cost:915.040527
Epoch   4/20 Cost:287.936096
Epoch   5/20 Cost:91.371063
Epoch   6/20 Cost:29.758249
Epoch   7/20 Cost:10.445267
Epoch   8/20 Cost:4.391237
Epoch   9/20 Cost:2.493121
Epoch  10/20 Cost:1.897688
Epoch  11/20 Cost:1.710552
Epoch  12/20 Cost:1.651416
Epoch  13/20 Cost:1.632369
Epoch  14/20 Cost:1.625924
Epoch  15/20 Cost:1.623420
Epoch  16/20 Cost:1.622152
Epoch  17/20 Cost:1.621262
Epoch  18/20 Cost:1.620501
Epoch  19/20 Cost:1.619757
Epoch  20/20 Cost:1.619046


In [ ]:
# nn.Module 및 F.mse_loss 사용
import torch.nn as nn
import torch.nn.functional as F
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3,1)
  def forward(self,x):
    return self.linear(x)
# 데이터
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])
# 모델 초기화
model=MultivariateLinearRegressionModel()
# optimizer 설정
optimizer=optim.SGD(model.parameters(),lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):
  # H(x) 계산
  prediction=model(x_train)
  # cost 계산
  cost=F.mse_loss(prediction,y_train)
  # cost로 H(x) 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  # 결과 출력
  print('Epoch{:4d}/{} Cost:{:.6f}'.format(
      epoch,nb_epochs,cost.item()
  ))

Epoch   0/20 Cost:44249.324219
Epoch   1/20 Cost:13878.036133
Epoch   2/20 Cost:4358.244141
Epoch   3/20 Cost:1374.290527
Epoch   4/20 Cost:438.974854
Epoch   5/20 Cost:145.798813
Epoch   6/20 Cost:53.899284
Epoch   7/20 Cost:25.089352
Epoch   8/20 Cost:16.054543
Epoch   9/20 Cost:13.218239
Epoch  10/20 Cost:12.324946
Epoch  11/20 Cost:12.040476
Epoch  12/20 Cost:11.946979
Epoch  13/20 Cost:11.913299
Epoch  14/20 Cost:11.898372
Epoch  15/20 Cost:11.889383
Epoch  16/20 Cost:11.882178
Epoch  17/20 Cost:11.875566
Epoch  18/20 Cost:11.869100
Epoch  19/20 Cost:11.862763
Epoch  20/20 Cost:11.856400


In [ ]:
# Loading Data (4-2)

In [ ]:
# PyTorch Dataset
from torch.utils.data import Dataset
class CustomDataset(Dataset):
  def __init__ (self):
    self.x_data=[[73,80,75],
                 [93,88,93],
                 [89,91,90],
                 [96,98,100],
                 [73,66,70]]
    self.y_data=[[152],[185],[180],[196],[142]]
  def __len__ (self):
    return len(self.x_data) # 데이터셋의 총 데이터 수
  def __getitem__ (self,idx):
    x=torch.FloatTensor(self.x_data[idx])
    y=torch.FloatTensor(self.y_data[idx])
    return x,y # 입력된 인덱스에 상응하는 입출력 데이터 반환

In [ ]:
# PyTorch DataLoader
dataset=CustomDataset()
from torch.utils.data import DataLoader
dataloader=DataLoader(
    dataset,
    batch_size=2, # 각 minibatch의 크기 (2의 제곱수)
    shuffle=True, # epoch마다 데이터셋을 섞어서 데이터 학습 순서를 바꿈
)

In [ ]:
# Full Code with Dataset and DataLoader
nb_epochs=20
for epoch in range(nb_epochs+1):
  for batch_idx,samples in enumerate(dataloader): # minibatch 인덱스와 데이터 받기
    x_train,y_train=samples
    # H(x) 계산
    prediction=model(x_train)
    # cost 계산
    cost=F.mse_loss(prediction,y_train)
    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    # 결과 출력
    print('Epoch{:4d}/{} Batch {}/{} Cost:{:.6f}'.format(
        epoch,nb_epochs,batch_idx+1,len(dataloader),cost.item()
    ))


Epoch   0/20 Batch 1/3 Cost:3.131616
Epoch   0/20 Batch 2/3 Cost:17.234631
Epoch   0/20 Batch 3/3 Cost:23.295912
Epoch   1/20 Batch 1/3 Cost:21.449482
Epoch   1/20 Batch 2/3 Cost:12.413155
Epoch   1/20 Batch 3/3 Cost:12.666631
Epoch   2/20 Batch 1/3 Cost:9.947742
Epoch   2/20 Batch 2/3 Cost:21.045195
Epoch   2/20 Batch 3/3 Cost:4.590249
Epoch   3/20 Batch 1/3 Cost:2.232791
Epoch   3/20 Batch 2/3 Cost:17.363939
Epoch   3/20 Batch 3/3 Cost:23.739300
Epoch   4/20 Batch 1/3 Cost:20.853479
Epoch   4/20 Batch 2/3 Cost:6.330982
Epoch   4/20 Batch 3/3 Cost:9.933423
Epoch   5/20 Batch 1/3 Cost:8.901110
Epoch   5/20 Batch 2/3 Cost:15.282537
Epoch   5/20 Batch 3/3 Cost:21.228056
Epoch   6/20 Batch 1/3 Cost:22.782278
Epoch   6/20 Batch 2/3 Cost:9.207287
Epoch   6/20 Batch 3/3 Cost:17.381760
Epoch   7/20 Batch 1/3 Cost:5.900721
Epoch   7/20 Batch 2/3 Cost:36.088470
Epoch   7/20 Batch 3/3 Cost:2.239986
Epoch   8/20 Batch 1/3 Cost:1.570729
Epoch   8/20 Batch 2/3 Cost:17.433086
Epoch   8/20 Batch 3/3 